import requests
import json

def generate_embeddings(prompt):
    """
    Generate embeddings for a given prompt using the nomic-embed-text model.
    
    Args:
        prompt (str): The text prompt for which embeddings are to be generated.
    
    Returns:
        list: A list of embeddings generated by the model.
    """
    # Define the API endpoint
    url = "http://localhost:11434/api/embeddings"
    
    # Prepare the payload
    payload = {
        "model": "nomic-embed-text",
        "prompt": prompt
    }
    
    try:
        # Send a POST request to the Ollama API
        response = requests.post(url, data=json.dumps(payload), headers={"Content-Type": "application/json"})
        
        # Check if the request was successful
        if response.status_code == 200:
            embeddings = response.json().get("embedding", [])
            return embeddings
        else:
            print(f"Error: {response.status_code} - {response.text}")
            return None
    except requests.RequestException as e:
        print(f"Request failed: {e}")
        return None

# Example usage
if __name__ == "__main__":
    text_prompt = "The sky is blue because of Rayleigh scattering."
    embeddings = generate_embeddings(text_prompt)
    
    if embeddings:
        print(f"Generated embeddings: {embeddings}")
    else:
        print("Failed to generate embeddings.")
